### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by gthieleb** [hsolbrig/dict_compare#1]
```
>>> import dict_compare
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gt0015/Development/Python/envs/provisioning/local/lib/python2.7/site-packages/dict_compare/__init__.py", line 30, in <module>
    from dict_compare.dict_compare import dict_compare, compare_dicts
  File "/home/gt0015/Development/Python/envs/provisioning/local/lib/python2.7/site-packages/dict_compare/dict_compare.py", line 34
    def compare_dicts(d1: dict, d2: dict, d1name: str="dict1", d2name: str="dict2", file=sys.stdout,
                        ^
SyntaxError: invalid syntax
```

**Comment by hsolbrig** [comment]
Apologies - dict_compare only works with python 3.
